version: '3'

services:
  apache:
    image: "httpd:2.4-alpine"
    expose:
      - 80
    ports:
      - "7979:80"
    volumes:
      - "./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "./web:/usr/local/apache2/htdocs"
    depends_on:
      - php

  php:
    image: php:8.2-fpm-alpine
    expose:
      - 9000
    command: php-fpm -F
    volumes:
      - "./web:/usr/local/apache2/htdocs"
